services:
  database:
    container_name: database
    image: postgres:16.4
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    restart: always
    networks:
      - container-network
    
  pgadmin:
      container_name: pgadmin
      image: dpage/pgadmin4
      depends_on:
        - database
      ports:
        - "${PGADMIN_PORT}:80"
      environment:
        PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      restart: always
      networks:
        - container-network

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: server
    depends_on:
      - database
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - DB_HOSTNAME=database
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_SSLMODE=${DB_SSLMODE}
    networks:
      - container-network

  proxy:
    image: nginx:1.25
    container_name: proxy
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - server
    networks:
      - container-network

volumes:
  db-data:

networks:
  container-network:
    driver: bridge